Create circle.yml
callstack-io/generator-node-module pull request #7
Opened 2017-08-26 17:20 UTC by satya164

2017-08-28 18:31 UTC, zamotany requested changes
The conflicts needs to be resolved. Also I would prefer to have a config for Circle 2.0

2017-08-28 18:31 UTC, zamotany commented
If you don't want to do it, that's totally fine.

2017-08-28 18:52 UTC, satya164 commented
I'll try to do it

2017-10-03 11:50 UTC, jukben commented
What about this one? cc @zamotany @satya164

2018-05-20 16:30 UTC, closed without merging